---
- hosts: all
  tasks:
    - name: "Add authorized keys"
      copy:
        src: authorized_keys
        dest: /root/.ssh/authorized_keys
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
        autoremove: yes
    
    - name: "Install snapd"
      apt:
        name: snapd
        state: present

    - name: "Install microk8s"
      community.general.snap:
        name: microk8s
        state: present
        classic: yes

- hosts: all
  tasks:
    - name: "Install wireguard"
      apt:
        name: wireguard
        state: present
        
    - name: reset
      file:
        path: /etc/wireguard/wg0.conf
        state: absent

    - name: "create wireguard keypair"
      shell:
        cmd: "wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey"
        creates: "/etc/wireguard/*key"
          
    - name: "retrieve wireguard public key"
      block:
        - slurp:
            src: /etc/wireguard/publickey
          register: slurpfile
        - set_fact:
            wireguard_publickey: "{{ slurpfile['content'] | b64decode }}"

- hosts: all
  tasks:
    - name: "Create wireguard server configuration"
      blockinfile:
        path: /etc/wireguard/wg0.conf
        create: yes
        marker: "#WIREGUARD INTERFACE CONFIG"
        block: |
          [Interface]
          PrivateKey = /etc/wireguard/privatekey
          Address = {{wg0_ip}}/24
          ListenPort = {{wg0_port}}
          SaveConfig = false

    - blockinfile:
        path: /etc/wireguard/wg0.conf
        marker: "#PEER {{item}}"
        block: |
          [Peer]
          PublicKey = {{hostvars[item].wireguard_publickey}}
          {%if hostvars[item].wg0_endpoint is defined %}
          Endpoint = {{ hostvars[item].wg0_endpoint }}
          {%endif%}
      loop: "{{ groups['kubevpc'] }}"
